---
title: 'STAT 542: Final Project'
author: "Karthik Vasu (kvasu2), Yining Lu (yining13)"
date: 'Due: 05/05/2022'
theme: readable
output:
  pdf_document:
    toc: yes
    toc_depth: 2
bibliography: references.bib
header-includes:
  - \usepackage{amsmath}
---

```{r, echo=FALSE}
train = read.csv("dataset/fashion-mnist_train.csv")
test = read.csv("dataset/fashion-mnist_test.csv")
```

```{r}
Xtrain = train[,2:785]
Ytrain = train[,1]
mXtrain = as.matrix(Xtrain)

Xtest = test[,2:785]
Ytest = test[,1]
```

# Summary Statistics

Data table

```{r, echo=FALSE}
table(Ytrain)
table(Ytest)
```

# Pre-Process

```{r}
trainMean = apply(Xtrain,2,mean)
trainSd = apply(Xtrain,2,sd)
Xtrain.sca = scale(Xtrain)
Xtest.sca = sweep(sweep(Xtest, 2L, trainMean), 2, trainSd, "/")
```

# Random Forest

```{r, warning=F}
# random forest
library(ranger)
rf.fit = ranger(as.factor(label)~., data=train, 
                importance="impurity", num.tree=500, probability=T)
print(rf.fit)
```

```{r, warning=F}
# predict by random forest
pred_tree = predict(rf.fit, test)$predictions
Ytest_pred_tree = rep(NA, nrow(Xtest))
# error for random forest
for (i in 1:nrow(Xtest)) {
  Ytest_pred_tree[i] = which.max(pred_tree[i,])-1
}
# confusion matrix
confuse_tree = table(Ytest, Ytest_pred_tree)
# mis-classification rate
misclass_rate_tree = rep(NA, 10)
number = rep(NA, 10)
for (i in 1:10) {
  misclass_rate_tree[i] = 1 - confuse_tree[i,i]/sum(confuse_tree[,i])
}
class = 0:9
misclass_tree = cbind(class, round(misclass_rate_tree,3))
# overall mis-classification rate
overall_misclass_tree = mean(Ytest_pred_tree != Ytest)
confuse_tree
misclass_tree
overall_misclass_tree
```

# SVM

```{r}
# kernel SVM and linear SVM
library(kernlab)
k = 1
index = list()
lsvm.fit = list()
svm.fit = list()
for (i in 1:10) {
  index[[i]] = which(Ytrain == i-1)
}
for (i in 1:9) {
  for (j in (i+1):10) {
    ind = c(index[[i]], index[[j]])
    x = mXtrain[ind,]
    y = c(rep(1, length(index[[i]])), rep(0, length(index[[j]])))
    lsvm.fit[[k]] = ksvm(x, y, type="C-svc", kernel="vanilladot", C=10, scaled=c())
    svm.fit[[k]] = ksvm(x, y, type="C-svc", kernel="rbfdot", C=10, scaled=c())
    k = k+1
  }
}
lvote = list()
vote = list()
for (i in 1:45) {
  lvote[[i]] = predict(lsvm.fit[[i]], Xtest)
  vote[[i]] = predict(svm.fit[[i]], Xtest)
}
```

```{r}
# predict by kernel SVM
Ytest_pred_svm = rep(NA, length(Ytest))
for (l in 1:length(Ytest)) {
  k = 1
  vote_list = c()
  for (i in 1:9) {
    for (j in (i+1):10) {
      if (vote[[k]][l] == 1)
        current_vote = i-1
      else
        current_vote = j-1
      vote_list = c(vote_list, current_vote)
      k = k + 1
    }
  }
  Ytest_pred_svm[l] = names(which.max(table(vote_list)))
}
# confusion matrix
confuse_svm = table(Ytest, Ytest_pred_svm)
# mis-classification rate
misclass_rate_svm = rep(NA, 10)
for (i in 1:10) {
  misclass_rate_svm[i] = 1 - confuse_svm[i,i]/sum(confuse_svm[,i])
}
class = 0:9
misclass_svm = cbind(class, round(misclass_rate_svm,3))
# overall mis-classification rate
overall_misclass_svm = mean(Ytest_pred_svm != Ytest)
confuse_svm
misclass_svm
overall_misclass_svm
```

```{r}
# predict by linear SVM
Ytest_pred_lsvm = rep(NA, length(Ytest))
for (l in 1:length(Ytest)) {
  k = 1
  vote_list = c()
  for (i in 1:9) {
    for (j in (i+1):10) {
      if (lvote[[k]][l] == 1)
        current_vote = i-1
      else
        current_vote = j-1
      vote_list = c(vote_list, current_vote)
      k = k + 1
    }
  }
  Ytest_pred_lsvm[l] = names(which.max(table(vote_list)))
}
# confusion matrix
confuse_lsvm = table(Ytest, Ytest_pred_lsvm)
# mis-classification rate
misclass_rate_lsvm = rep(NA, 10)
for (i in 1:10) {
  misclass_rate_lsvm[i] = 1 - confuse_lsvm[i,i]/sum(confuse_lsvm[,i])
}
class = 0:9
misclass_lsvm = cbind(class, round(misclass_rate_lsvm,3))
# overall mis-classification rate
overall_misclass_lsvm = mean(Ytest_pred_lsvm != Ytest)
confuse_lsvm
misclass_lsvm
overall_misclass_lsvm
```

# Save

```{r}
save.image(file ="RData/rf_svm.RData")
```